[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
from = "/"
  to = "https://bitmona.github.io/TacoProxyV2/"
  status = 200
  force = true
  conditions = {Role = ["admin", "cms"]}
