[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/search"
  to = "https://Nebula.bitmona.repl.co"
  status = 200
  force = true
