[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/search"
  to = "https://bitmona.github.io/TacoProxyV2/public"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
