[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/search"
  to = "https://holyubofficial.net/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
